// web/src/app/layouts/demo4/header/header.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "[app-header]",
  imports: [],
  templateUrl: "./header.component.html",
  styleUrl: "./header.component.scss",
})
export class HeaderComponent {}

<!-- Header -->
<header class="flex lg:hidden items-center fixed z-10 top-0 start-0 end-0 shrink-0 bg-muted h-(--header-height)" id="header">
    <!-- Container -->
    <div class="kt-container-fluid flex items-center justify-between flex-wrap gap-3">
        <a href="#">
            <img alt="" class="dark:hidden min-h-[30px]" src="assets/media/app/mini-logo-gray.svg"/>
            <img alt="" class="hidden dark:block min-h-[30px]" src="assets/media/app/mini-logo-gray-dark.svg"/>
        </a>
        <button class="kt-btn kt-btn-icon kt-btn-ghost -me-2" data-kt-drawer-toggle="#sidebar">
            <i class="ki-filled ki-menu">
            </i>
        </button>
    </div>
    <!-- End of Container -->
</header>
<!-- End of Header -->

// web/src/components/layouts/layout-16/components/header.tsx
import { useState } from 'react';
import { Menu } from 'lucide-react';
import { Link } from 'react-router';
import { toAbsoluteUrl } from '@/lib/helpers';
import { Button } from '@/components/ui/button';
import {
  Sheet,
  SheetBody,
  SheetContent,
  SheetHeader,
  SheetTrigger,
} from '@/components/ui/sheet';
import { useLayout } from './context';
import { HeaderTitle } from './header-title';
import { HeaderToolbar } from './header-toolbar';
import { SidebarPrimary } from './sidebar-primary';
import { SidebarSecondary } from './sidebar-secondary';

export function Header() {
  const { isMobile } = useLayout();
  const [isSheetOpen, setIsSheetOpen] = useState(false);

  return (
    <header className="fixed top-0 start-0 lg:start-(--sidebar-width) end-0 z-50 flex items-center shrink-0 bg-background/95 backdrop-blur-sm supports-backdrop-filter:bg-background/60 h-(--header-height-mobile) lg:h-[var(--header-height)] pe-[var(--removed-body-scroll-bar-size,0px)]">
      <div className="container-fluid grow flex items-center justify-between gap-2">
        {/* Mobile sidebar toggle */}
        {isMobile && (
          <div className="flex items-center gap-2">
            <Link to="/layout-16">
              <img
                src={toAbsoluteUrl('/media/app/mini-logo-gray-dark.svg')}
                className="dark:hidden min-h-[30px]"
                alt="Logo"
              />
              <img
                src={toAbsoluteUrl('/media/app/mini-logo-gray.svg')}
                className="hidden dark:block min-h-[30px]"
                alt="Logo"
              />
            </Link>
            <Sheet open={isSheetOpen} onOpenChange={setIsSheetOpen}>
              <SheetTrigger asChild>
                <Button variant="ghost" mode="icon" size="sm">
                  <Menu className="size-4" />
                </Button>
              </SheetTrigger>
              <SheetContent
                className="p-0 gap-0 w-[300px]"
                side="left"
                close={false}
              >
                <SheetHeader className="p-0 space-y-0" />
                <SheetBody className="flex grow p-0">
                  <SidebarPrimary />
                  <SidebarSecondary />
                </SheetBody>
              </SheetContent>
            </Sheet>
          </div>
        )}

        {!isMobile && <HeaderTitle />}
        <HeaderToolbar />
      </div>
    </header>
  );
}
